config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /es|en/ do
    devise_for :users
    resources :pins
  end

  get '/:locale', to: 'pages#index', as: :home

  get '/:locale/about', to: 'pages#about', as: :about
  get '/:locale/contact', to: 'pages#contact', as: :contact

  root 'pages#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  validates :photo, presence: true
  validates :title, presence: true
  validates :description, presence: true

  belongs_to :user

  after_create :update_slug
  before_create :assign_slug

  def to_param
    slug
  end

  private

  def assign_slug
    self.slug = "#{title.parameterize}"
  end

  def update_slug
    update_attributes slug: assign_slug
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_locale
    I18n.locale = params[:locale] ||
                  extract_locale_from_accept_language_header ||
                  I18n.default_locale
  end

  def default_url_options(options={})
    { locale: I18n.locale }
  end

  private

  def extract_locale_from_accept_language_header
    locale = request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    locale if ['es', 'en'].include? locale.to_s
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user = current_user

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title><%= yield :title %></title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navbar' %>

<div class="container">
  <%= flash_messages %>
</div>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>
  My About Page
<% end %>

<div class="jumbotron">
  <div class="container">
    <h1><%= t('about_title') %></h1>
    <p><a class="btn btn-primary btn-lg" href="#" role="button"><span class="glyphicon glyphicon-pushpin"></span><%= t('learn') %></a></p>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
    <div class="page-header">
      <h2>Example page header <small>Subtext for header</small></h2>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <a href="" title="Un Link">Un Link <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span></a>
    </div>
    <div class="col-md-4">
      <div class="page-header">
        <h2>Subtitulo <small>Subtext for header<span class="label label-default">New</span></small></h2>
      </div>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    <div class="col-md-4">
      <div class="page-header">
        <h2>Example page header <small>Subtext for header</small></h2>
      </div>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <img src="https://autosytecnologia.files.wordpress.com/2011/12/audi-rojo.jpg" class="img-responsive" alt="">
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<% content_for :title do %>
  Pagina de Contacto
<% end %>

<div class="jumbotron">
  <div class="container">
  	<h1><%= t('contact_title') %></h1>
  	<p><a class="btn btn-primary btn-lg" href="#" role="button"><span class="glyphicon glyphicon-pushpin"></span>Learn more</a></p>
  </div>
</div>

<div class="container">
	<div class="row">
	  <div class="col-md-6">
		<div class="page-header">
		  <h2>Example page header <small>Subtext for header</small></h2>
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<a href="" title="Un Link">Un Link <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span></a>
	  </div>
	  <div class="col-md-6">
	  	<div class="page-header">
	  		<h2>Subtitulo <small>Subtext for header<span class="label label-default">New</span></small></h2>
	  	</div>
	  	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	  	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	  	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	  	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	  	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	  	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	  </div>
	</div>
</div>

app/views/pages/index.html.erb
<% content_for :title do %>
  Mi pinterest
<% end %>

<div class="jumbotron">
  <div class="container">
  	<h1><%= t('hello') %></h1>
  	<p><a class="btn btn-primary btn-lg" href="#" role="button"><span class="glyphicon glyphicon-pushpin"></span>Learn more</a></p>
  </div>
</div>

<div class="container">
	<div class="row">
	  <div class="col-md-4">
		<div class="page-header">
		  <h2>Example page header <small>Subtext for header</small></h2>
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<a href="" title="Un Link">Un Link <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span></a>
	  </div>
	  <div class="col-md-4">
	  	<div class="page-header">
	  		<h2>Subtitulo <small>Subtext for header<span class="label label-default">New</span></small></h2>
	  	</div>
	  	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	  	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	  	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	  	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	  	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	  	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	  </div>
	  <div class="col-md-4">
	  	<div class="page-header">
	  	  <h2>Example page header <small>Subtext for header</small></h2>
	  	</div>
	  	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	  	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	  	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	  	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	  	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	  	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	  	<img src="https://autosytecnologia.files.wordpress.com/2011/12/audi-rojo.jpg" class="img-responsive" alt="">
	  </div>
	</div>
</div>

app/views/pins/_form.html.erb
<div class="col-md-6">
  <%= form_for(@pin) do |f| %>
    <% if @pin.errors.any? %>
      <div id="error_explanation">
        <h4 class="bg-danger"><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h4>

        <ul class="bg-warning">
        <% @pin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <div class="field">
        <%= f.label :photo, 'Imagen' %><br>
        <%= f.text_field :photo, class: 'form-control', placeholder: 'URL de la imagen' %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :title, 'Titulo' %><br>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Nombre del pin' %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :description, 'Descripcion' %><br>
        <%= f.text_area :description, class: 'form-control', rows: '10' %>
      </div>
    </div>

    <div class="form-group">
      <div class="actions">
        <%= f.submit 'Crear', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/edit.html.erb
<div class="container">
	<h1><%= t('edit_pin') %></h1>

	<div class="row">
		<%= render 'form' %>
	</div>

	<%= link_to 'Show', @pin %> |
	<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.slim
.container
  .page-header
    h1
      = t('listing_pins')
      small
        = t('fav_pins')
    - if user_signed_in?
        = link_to t('new_pin'), new_pin_path, class: 'btn btn-success'
  .row
    - @pins.each do |pin|
      .col-md-3
        .thumbnail
          = image_tag pin.photo, class: 'img-responsive'
          .caption
            h4 = pin.title
            p = pin.description
            .buttons-group
              = link_to t('show'), pin, class: 'btn btn-primary'
              - if user_signed_in?
                =link_to t('edit'), edit_pin_path(pin), class: 'btn btn-warning'
                = link_to t('destroy'), pin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/pins/new.html.erb
<div class="container">
	<h1><%= t('new_pin') %></h1>

	<div class="row">
		<%= render 'form' %>
	</div>

	<%= link_to 'Back', pins_path, class: 'btn btn-info' %>
</div>

app/views/pins/show.html.slim
p#notice = notice

p
  strong Photo:
  '
  = image_tag @pin.photo, style: 'width:200px'
p
  strong Title:
  '
  = @pin.title
p
  strong Description:
  '
  = @pin.description

p
  = link_to 'Edit', edit_pin_path(@pin)
  '  |
  = link_to 'Back', pins_path

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Mi Pinterest', home_path, class: "navbar-brand"  %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to t('about'), about_path  %></li>
          <li><%= link_to t('pins'), pins_path  %></li>
          <li><%= link_to t('contact'), contact_path  %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
          <li><%= link_to 'Ingresar', new_user_session_path %></li>
          <li><%= link_to 'Registrar', new_user_registration_path %></li>
        <% else %>
          <li><%= link_to current_user.name, edit_user_registration_path %></li>
          <li><%= link_to 'Salir', destroy_user_session_path, method: :delete, data: { confirm: "Seguro que desea salir?" } %></li>
        <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div>
</nav>